---
title: "MLA_CIA1"
author: "Meghna John"
date: '2024-07-14'
output:
  pdf_document: default
  html_document: default
---

```{r}
library(readr)
library(dplyr)
library(psych)
library(DataExplorer)
library(MASS)
library(glmnet)
# Load the dataset
data<-read_csv('C://Users//hp//Downloads//ObesityDataSet_raw_and_data_sinthetic.csv')
head(data)
names(data)
```

```{r}
# Check for missing values
summary(data)
is.na(data)
plot_missing(data)
```

```{r}
# Converting categorical variables to numeric
data$Gender<-as.numeric(as.factor(data$Gender))
data$family_history_with_overweight<-as.numeric(as.factor(data$family_history_with_overweight))
data$FAVC<-as.numeric(as.factor(data$FAVC))
data$CAEC<-as.numeric(as.factor(data$CAEC))
data$SMOKE<-as.numeric(as.factor(data$SMOKE))
data$SCC<-as.numeric(as.factor(data$SCC))
data$CALC<-as.numeric(as.factor(data$CALC))
data$MTRANS<-as.numeric(as.factor(data$MTRANS))
data$NObeyesdad<-as.numeric(as.factor(data$NObeyesdad))
```

```{r}
# Split the data into training and testing sets
set.seed(123)
mixed_data<-data[order(runif(2111)),]
train_data<-mixed_data[1:1478,]
test_data<-mixed_data[1479:2111,]

# Separating features and target variable
x_train<-model.matrix(NObeyesdad~.,data=train_data)
y_train<-train_data$NObeyesdad
x_test<-model.matrix(NObeyesdad~.,data=test_data)
y_test<-test_data$NObeyesdad

```

```{r}
# Train the model
model<-lm(NObeyesdad~.,data=train_data)
# Model summary
summary(model)

#Model Evaluation
model_step=stepAIC(model,direction='backward')

#Training the best model
best_model<-lm(NObeyesdad~Age+Height+Weight+family_history_with_overweight+FAVC+FCVC+NCP+CAEC+CH2O+SCC+FAF,data=train_data)
# Model summary
summary(best_model)
# Predict and evaluate on test data
fullmodel_pred<-predict(best_model,newdata=test_data)
fullmodel_pred
# Calculate performance metrics
fullmodel<-summary(best_model)$r.squared
fullmodel_test<-cor(test_data$NObeyesdad,fullmodel_pred)^2

# Compare R-squared values
cat("Full Model - Train R2:",fullmodel,"Test R2:",fullmodel_test, "\n")

```

```{r}
#Building Ridge and Lasso Models

#Defining the lambda sequence
lambda <- 10^seq(2,-2,length=-0.1)
print(lambda)

# Ridge Regression
ridge_model<-train(x=x_train,y=y_train,method="glmnet",alpha=0,lambda=lambda)
summary(ridge_model)
# Predictions and evaluation for ridge model
ridge_predictions<-predict(ridge_model,newx=x_test)
ridge_rmse<-RMSE(ridge_predictions,y_test)
ridge_r2<-R2(ridge_predictions,y_test)



# Lasso Regression
lasso_model<-glmnet(x_train,y_train,alpha=1,lambda=lambda)
lasso_predictions<-predict(lasso_model,newx=x_test)
lasso_rmse<-RMSE(lasso_predictions,y_test)
lasso_r2<-R2(lasso_predictions,y_test)
```


```{r}


#Lean model Evaluation
lm_mla1_step=stepAIC(model,direction='backward')
lm_mla1_step=stepAIC(model,direction='forward')

```